// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/information/sample/delete": {
            "post": {
                "tags": [
                    "标签"
                ],
                "summary": "删除样本列表数据",
                "responses": {}
            }
        },
        "/api/v1/information/sample/get": {
            "get": {
                "tags": [
                    "标签"
                ],
                "summary": "获取样本列表数据",
                "responses": {}
            }
        },
        "/api/v1/information/sample/insert": {
            "post": {
                "tags": [
                    "标签"
                ],
                "summary": "新增样本信息",
                "responses": {}
            }
        },
        "/api/v1/information/sample/update": {
            "get": {
                "tags": [
                    "标签"
                ],
                "summary": "更新样本信息",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
